### ISSUE TITLE
How to decrypt file or stream?

### ISSUE THREAD

**Issue by ozjongwon** [greglook/clj-pgp#11]
Hi,

Could you point the best way to decrypt file or input stream? (i.e., got an encrypted file and need to decrypt)

Thanks!

- J

**Comment by ozjongwon** [comment]
Sorry this was my misunderstanding. Somehow my example encrypted file encrypted using subkey instead of primary key and caused problem.

**Comment by greglook** [comment]
Glad you figured it out!
