### ISSUE TITLE
MessagePacket extension for PGPMarker

### ISSUE THREAD

**Issue by ozjongwon** [greglook/clj-pgp#12]
Hi Greg,

I am using clj-pgp to deal with an old service provider who uses old pgp (thanks for a great software!)

When I try to decrypt an encrypted file given by the provider, I got:

```
IllegalArgumentException No implementation of method: :unpack-message of protocol: #'clj-pgp.message/MessagePacket found for class: org.bouncycastle.openpgp.PGPMarker  clojure.core/-cache-protocol-fn (core_deftype.clj:554)
```

Based on bouncycasle doc(https://bouncycastle.org/docs/pgdocs1.5on/org/bouncycastle/openpgp/PGPMarker.html), this should be ignored.

So my quick extension is:

``` clojure
;; import PGPMarker, etc
(extend-protocol MessagePacket
  PGPMarker
  (unpack-message
    [packet opts]
    []))
```

Two things, I am not sure if this is fine(i.e., need your confirmation :) and you may want to add this to your great software.

Thanks again!
- J

**Comment by greglook** [comment]
Fixed in #21
