### ISSUE TITLE
Can't decrypt messages encrypted with GnuPG

### ISSUE THREAD

**Issue by cesarolea** [greglook/clj-pgp#13]
I generated my keys using GnuPG. If I both encrypt and decrypt a message using this library, it works perfectly fine. If I encrypt a message for someone else using their imported public key, they can decrypt it just fine. However if I encrypt a message with my public key using GnuPG and then try to decrypt it using this library, it fails with the following message:

>IllegalArgumentException Cannot decrypt #<PGPEncryptedDataList >org.bouncycastle.openpgp.PGPEncryptedDataList@24fedc7e> with {:decryptor #<PGPPrivateKey >org.bouncycastle.openpgp.PGPPrivateKey@329ab06e>} (no matching encrypted session key)  clj-pgp.message/eval2719/fn--2720 (message.clj:255)

The same message can be decrypted ok using the GnuPG binary.

These are my functions:

```clojure
(defn get-pubkey
  []
  (first (keyring/list-public-keys @private-keyring)))

(defn get-seckey
  []
  (keyring/get-secret-key @private-keyring (pgp/hex-id (get-pubkey))))

(defn get-private-key
  [password]
  (pgp/unlock-key (get-seckey) password))

(defn encrypt
  ([message]
   (pgp-msg/encrypt
    message
    (get-pubkey)
    :format :utf8
    :cipher :aes-256
    :compress :zip
    :armor true))
  ([message pubkey]
   (pgp-msg/encrypt
    message
    (get @public-keys pubkey)
    :format :utf8
    :cipher :aes-256
    :compress :zip
    :armor true)))

(defn decrypt
  ([message]
     (pgp-msg/decrypt message (get-private-key (gpg-key))))
  ([message password]
   (pgp-msg/decrypt message (get-private-key password))))
```

So if I do

```clojure
(decrypt (encrypt "Hello World!") "my secret password")
```

It works as intended. However if I try to do:

```clojure
(def test-msg "-----BEGIN PGP MESSAGE-----\nVersion: GnuPG v1\n\nhQIMA72hwX+6DdOZARAAhP2WFT62e/iqTECVXUmUu/Zj93hrAXBND3IyXLYjM5Un\nfcOg3U2TTZq/aA9bepP0j81q2oy76qq7AtFBnmTRzZGIHbyRzV5xjVXb9uwciXF+\n8lhs1dZzOxvG1Hdh5J4VS4IHBmaqSsJxubw7PrWAeiWlDpJlmEsphx/fmVQYtodO\n9BTu3PKqfpl1eNDG7791ZfETUhN0M6m2doDGt3ERWxEJlffl6smchExpJftfogmd\nC8GNSZ+mYwg/RzmEHPpyyqzOzreau0Ezmaz5jlTuR+iCdB9IFQySYb+FYa+yzNeI\nwQV2gIfntLT0u6GMx3LgW45bPQDi6ZxJXa85MQEhdkLISgSlFZ6fKo2O0fdoxmhV\nvwtNXNJEyiKtDZfmQ4IuoxA5rin54HrFxzsv/8LgRZrZlVMtA+BqL4xS/VXSC6L4\nBQXIG15N19ZUe63kjIMLpWkoUbW141XYXiqewla7/f4aJ/v+zZuFxU5LaLcK5WTN\nZ1oHgeS/7TF7/uoXBlT6esyO6WCINZbSTmoAy8/jglk+F4bxbKFCy+tCVVWAdBh2\nc+rnyzEXOd8QCe0/SolpBat3iXwdzOhwsSod8urUj5/62NLTfExKEyg70QzgOA+O\ni/3/gXVWcrdi/vtNoX+mlJQH/G9fhEuMonwGL+SJTBkBa6HXnPKxQ1GfHRvJcWTS\nPQFUjObImDPYneJPXzbzG/L90YZ+sjcZT7r6IURku89IPa3MI+wkRGowUA21bT3t\n+sLfF824zShc7Xq5jvA=\n=tJjv\n-----END PGP MESSAGE-----");

(decrypt test-msg "my secret password)
```

I get the exception above, but the same message can be decrypted by GnuPG using the proper private key and password. My test messages are being generated with GnuPG using:

```sh
gpg -a --encrypt -r vagrant@test.com --compress-algo zip --cipher-algo AES256
```

What am I missing?

**Comment by greglook** [comment]
Seems like things are going wrong in the [`unpack-message`](https://github.com/greglook/clj-pgp/blob/1ab44ad3471dc520236b631cda26dd0400a8c184/src/clj_pgp/message.clj#L299) implementation for `PGPPublicKeyEncryptedData`. This results in no matching secrets [here](https://github.com/greglook/clj-pgp/blob/1ab44ad3471dc520236b631cda26dd0400a8c184/src/clj_pgp/message.clj#L253). I'll try to reproduce this locally.

**Comment by cesarolea** [comment]
Thanks!

Let me know if you need my help reproducing the issue.

**Comment by ozjongwon** [comment]
This sounds familiar. I believe I got the error message when I used non encryption key  - a pubkey with {:encryption-key? false} as a part of return value of  pgp/key-info

(I couldn't remember more than that, unfortunately. Will add more info when I find some)

**Comment by ozjongwon** [comment]
Hmm... my previous comment is wrong - bad memory (totally different problem).

I forgot details but my git log shows I switched from use of master key to sub key to avoid this problem. I vaguely remember, bouncycastle does not like use of master key or thing like that. Therefore my conclusion was this was not cl-pgp's problem (and I didn't raise an issue)

**Comment by cesarolea** [comment]
You are right, so I changed the following in my code:

```clojure
(defn get-pubkey
  []
  (second (keyring/list-public-keys @private-keyring)))
```

To get the sub key, then it worked perfectly. Thank you so much for your assistance! it may be worthwhile to document it somewhere.

**Comment by greglook** [comment]
Hmm, interesting. Best practice with PGP is to use your master key _only_ for signing subkeys, so this makes sense. You could filter the public subkeys and find one with `(:encryption-key? (pgp/key-info pubkey))` true.

**Comment by malcolmsparks** [comment]
Thanks for this, I had the same problem and this write-up solved it for me.
