### ISSUE TITLE
encrypting with a user-id

### ISSUE THREAD

**Issue by priyatam** [greglook/clj-pgp#15]
Given a private key and public key, what is the equivalent of the following gpg encryption cmd?

    gpg -r <uid> --encrypt <filename>

Currently the api exposed by message.clj doesn't accept encryption to a recipient (uid, public key).

**Comment by greglook** [comment]
In the gpg command the `--recipient <name>` option is a way of looking up a matching public key in your public keyring. You could do this with this library by using `clj-pgp.keyring/list-public-keys` and filtering the results by the user id. Once you have the key, you can call `clj-pgp.message/encrypt` with it.
