### ISSUE TITLE
How do I wrap an InputStream for decryption?

### ISSUE THREAD

**Issue by coreagile** [greglook/clj-pgp#17]
Greetings,

I'm working with some low-level libraries that tend to do their data reading/writing using streams. I just found your library, and had a lot of fun working with it, and found `clj-pgp.message/encrypted-data-stream` but did not find an analog for decryption. Any chance I'm just confused and it's somewhere I am unable to find?

Thanks!
Stephen.

**Comment by greglook** [comment]
The functions you're looking for are [`decrypt`](https://greglook.github.io/clj-pgp/api/clj-pgp.message.html#var-decrypt) or the lower-level [`read-messages`](https://greglook.github.io/clj-pgp/api/clj-pgp.message.html#var-read-messages), depending on how much control you want. Both functions accept an input-stream (or anything that can be coerced to such) as their first argument.

**Comment by coreagile** [comment]
Oh! And they return an inputstream back?

Stephen Starkey, ACC, CSP-SM, CHP
forgiveness | bravery | honesty | fairness | leadership | creativity

**Comment by greglook** [comment]
No, not directly - `read-messages` will return you a lazy sequence of message packets with data in the `:data` key. You could map over that and use [`byte-streams/convert`](https://github.com/ztellman/byte-streams) to turn that into an input stream if you'd like.

**Comment by coreagile** [comment]
Thanks. I would rather not read some of these things into memory, so I ended up writing my own function using Java interop. Not quite confident in my understanding of the algorithm, but if you are interested in a pull request I’m happy to offer what I’ve built.. could be handy...

Stephen Starkey
empathy | connectedness | restorative | relator | belief
http://coreagile.co/coaching

**Comment by greglook** [comment]
The new 0.10.0 release includes a solution for this finally - `clj-pgp.message/reduce-messages` will pass the function you give it the input stream for each decrypted message body one at a time, so you can process them in a streaming fashion.
